[package]
name = "exilent"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "collector"] }
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"
stable-diffusion-a1111-webui-client = { git = "https://github.com/philpax/stable-diffusion-a1111-webui-client.git" }
anyhow = "1.0.66"
image = "0.24.4"
